builds:
  - binary: quarterback
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  files:
    - none*
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: tar.gz